version: '3.2'
services:
    
    gm1356_monitoring_db:
      image: mysql
      restart: on-failure
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      ports:
        - "13306:3306"
      volumes:
        - ./mysql-init:/docker-entrypoint-initdb.d
        - mysql_storage:/var/lib/mysql
    
    gm1356_monitoring_grafana:
      image: grafana/grafana
      restart: on-failure
      ports:
        - "13000:3000"
      volumes:
        - grafana_storage:/var/lib/grafana
volumes:
  grafana_storage:
  mysql_storage:
